# Generated by Django 2.2.7 on 2019-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('gene', models.TextField(blank=True, db_column='Gene', null=True)),
                ('nucleotide_change', models.TextField(blank=True, db_column='Nucleotide_Change', null=True)),
                ('protein_change', models.TextField(blank=True, db_column='Protein_Change', null=True)),
                ('other_mappings', models.TextField(blank=True, db_column='Other_Mappings', null=True)),
                ('alias', models.TextField(blank=True, db_column='Alias', null=True)),
                ('transcripts', models.TextField(blank=True, db_column='Transcripts', null=True)),
                ('region', models.TextField(blank=True, db_column='Region', null=True)),
                ('reported_classification', models.TextField(blank=True, db_column='Reported_Classification', null=True)),
                ('inferred_classification', models.TextField(blank=True, db_column='Inferred_Classification', null=True)),
                ('source', models.TextField(blank=True, db_column='Source', null=True)),
                ('last_evaluated', models.TextField(blank=True, db_column='Last_Evaluated', null=True)),
                ('last_updated', models.TextField(blank=True, db_column='Last_Updated', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', null=True)),
                ('submitter_comment', models.TextField(blank=True, db_column='Submitter_Comment', null=True)),
                ('assembly', models.TextField(blank=True, db_column='Assembly', null=True)),
                ('chr', models.TextField(blank=True, db_column='Chr', null=True)),
                ('genomic_start', models.TextField(blank=True, db_column='Genomic_Start', null=True)),
                ('genomic_stop', models.TextField(blank=True, db_column='Genomic_Stop', null=True)),
                ('ref', models.TextField(blank=True, db_column='Ref', null=True)),
                ('alt', models.TextField(blank=True, db_column='Alt', null=True)),
                ('accession', models.TextField(blank=True, db_column='Accession', null=True)),
                ('reported_ref', models.TextField(blank=True, db_column='Reported_Ref', null=True)),
                ('reported_alt', models.TextField(blank=True, db_column='Reported_Alt', null=True)),
            ],
            options={
                'verbose_name': 'Variants',
                'ordering': ['id'],
            },
        ),
    ]
